### PR TITLE
Make diffing stack safe

### LINKED ISSUE #14: Diffing is not stack safe
Hello, thank you for the great library! I've started using it in a project and have run into a `StackOverflowError` when diffing two XML elements with a lot of children.

I've put together a simple repository at https://github.com/mrdziuban/xml-diff-stack-safety to reproduce it. The [stack size is limited to 256K](https://github.com/mrdziuban/xml-diff-stack-safety/blob/main/build.sbt#L9) to reproduce the issue and triggers the error by diffing [an XML element that has 1000 children](https://github.com/mrdziuban/xml-diff-stack-safety/blob/main/src/main/scala/example/Test.scala#L6).

The full stack trace is:

<details><summary>expand stack trace</summary>

```
Exception in thread "main" java.lang.StackOverflowError
  at java.lang.Integer.toString(Integer.java:935)
  at scala.xml.Atom.text(Atom.scala:53)
  at com.github.andyglow.xml.diff.Lookup$Node.apply(Lookup.scala:42)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.$anonfun$compute$1(XmlDiffComputer.scala:72)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.$anonfun$compute$1$adapted(XmlDiffComputer.scala:72)
  at scala.collection.Iterator.indexWhere(Iterator.scala:414)
  at scala.collection.Iterator.indexWhere$(Iterator.scala:410)
  at scala.collection.AbstractIterator.indexWhere(Iterator.scala:1288)
  at scala.collection.SeqOps.indexWhere(Seq.scala:344)
  at scala.collection.SeqOps.indexWhere$(Seq.scala:344)
  at scala.collection.AbstractSeq.indexWhere(Seq.scala:1161)
  at scala.collection.SeqOps.indexWhere(Seq.scala:355)
  at scala.collection.SeqOps.indexWhere$(Seq.scala:355)
  at scala.collection.AbstractSeq.indexWhere(Seq.scala:1161)
  at com.github.andyglow.xml.diff.package$SeqNodeOps$.findAndDrop$extension(package.scala:37)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.contains$2(XmlDiffComputer.scala:72)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:84)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.matchChildren(XmlDiffComputer.scala:95
  at com.github.andyglow.xml.diff.XmlDiffComputer$.$anonfun$compute$2(XmlDiffComputer.scala:75)
  at scala.Option.map(Option.scala:242)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.contains$2(XmlDiffComputer.scala:74)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:86)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.compute(XmlDiffComputer.scala:87)
  at com.github.andyglow.xml.diff.XmlDiffComputer$.matchChildren(XmlDiffComputer.scala:95
  at com.github.andyglow.xml.diff.XmlDiffComputer$.computeMatching(XmlDiffComputer.scala:119)
  at com.github.andyglow.xml.diff.package$XmlOps$.$eq$hash$eq$extension(package.scala:30)
  at example.Test$.main(Test.scala:9)
  at example.Test.main(Test.scala)
```

</details>

Do you think it would be possible to make the diffing algorithm stack safe by using `@tailrec` annotations or [`scala.util.control.TailCalls` for trampolining](https://www.scala-lang.org/api/2.13.6/scala/util/control/TailCalls$.html)?

### PR DESCRIPTION
**Pull request by mrdziuban**
Fixes #14 

- Adds minimal version of [`cats.Eval`](https://github.com/typelevel/cats/blob/main/core/src/main/scala/cats/Eval.scala) which guarantees stack safety when using `map`/`flatMap`
- Updates all methods in `XmlDiffComputer` to wrap their results in `Eval`
- Sets the JVM stack size when running tests to 256K and adds a test to verify that diffing elements with a lot of children does not throw a `StackOverflowError`

### CODE REVIEW

File: src/main/scala/com/github/andyglow/xml/diff/XmlDiffComputer.scala [hunk 1]
```diff
@@ -62,67 +62,76 @@ private[diff] object XmlDiffComputer {
...
-    diff1 ++ diff2
   }
 
-  def computeMatching(e: xml.NodeSeq, a: xml.NodeSeq): XmlDiff = {
+  def computeMatching(e: xml.NodeSeq, a: xml.NodeSeq): Eval[XmlDiff] = {
     (e, a) match {
       case (e: xml.Elem, a: xml.Elem) =>
-        matchNames(e, a) ++
-        matchAttributes(e, a) ++
-        matchChildren(e.child, a.child) flatMap {
```
Comment (mrdziuban) [inline src/main/scala/com/github/andyglow/xml/diff/XmlDiffComputer.scala:119]: I wasn't 100% sure whether `flatMap` here was being called only on the result of `matchChildren(...)` or on the whole result of `(matchNames(...) ++ matchAttributes(...) ++ matchChildren(...)`, i.e. whether `++` or `flatMap` has higher precedence.

I settled on calling `flatMap` on the whole result based on this example that proved `++` has higher precedence:

```scala
List(1) ++ List(2) ++ List(3) flatMap { i => List(i, i) }
// List(1, 1, 2, 2, 3, 3)
```

Let me know if you see any issues here though

**Comment by mrdziuban** [comment]
@andyglow is there any chance you could review this and potentially release a new version if/when it's merged? Let me know if there's any more info or clarification I can provide

**Comment by andyglow** [comment]
No, no questions..
This looks great. Thank you for your contribution.
Except... May I ask you to hide `Eval` machinery making it a package private?

**Comment by mrdziuban** [comment]
Sure thing @andyglow, just pushed another commit to add `private[diff]`

**Review by andyglow — APPROVED** [review]
lgtm

**Comment by andyglow** [comment]
hey @mrdziuban
`3.0.1` has been published to sonatype
should be available in maven central soon

**Comment by mrdziuban** [comment]
Thank you!
